[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "printBuddies"
authors = [{name="Matt Manes"}]
description = "Handful of utilities to do printing tricks to the terminal."
version = "0.4.1"
requires-python = ">=3.6"
dependencies = [
	"noifTimer"
]
readme = "README.md"
keywords = [
    "terminal",
    "print",
    "printing",
    "progressbar"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/matt-manes/printBuddies"
"Documentation" = "https://github.com/matt-manes/printBuddies/tree/main/docs"
"Source code" = "https://github.com/matt-manes/printBuddies/tree/main/src/printBuddies"