[tool.poetry]
name = "use-case-outcome"
version = "0.1.0"
description = ""
authors = ["Ross Bown <rossbo@softcat.com>"]
readme = "README.md"
packages = [{include = "use_case_outcome"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
