[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "easy_dp"
version = "0.0.5"
authors = [
  { name="Tarasco Pier Paolo", email="pier.tarasco@gmail.com" },
]
description = "A not-so-efficient library for easy implementation of multi-gpu differential privacy"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Pier297/easy_dp"
"Bug Tracker" = "https://github.com/Pier297/easy_dp/issues"