[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "westat"
version = "0.0.6"
authors = [
  { name="py2cn", email="aboutlong@qq.com" },
]
description = "A package for stat and data miner,calculate woe and iv,and plot woe ,plot iv,calculate ks ,plot ks and auc,plot roc"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "http://www.pyminer.com"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"