[tool.poetry]
name = "UnderstandingImportsForTesting"
version = "0.9.0"
description = "Fixing imports in Python"
authors = ["Yashesh Dasari <yasheshdasari@gmail.com>"]
packages = [{include = "UnderstandingImportsForTesting"}, {include = "UnderstandingImportsForTesting/*.py"}]


[tool.poetry.dependencies]
python = "^3.6"
pathsingleton = "0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
