

[project]
name = "the_calc_pack_Pranav76"
version = "0.0.2"
authors = [
  { name="Pranav Gore", email="gpranav657@gmail.com" },
]
description = "This package helps you to carry out basic arithmetic operations"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]



[build-system]
requires = ["setuptools>=61.0","wheel"]
build-backend = "setuptools.build_meta"

