[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "postdantic"
version = "0.0.2"
authors = [
  { name="Omer Cohen", email="omercotkd@gmail.com" },
]
description = "ORM for Postgres using pydantic"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/omercotkd/postdantic"
"Bug Tracker" = "https://github.com/omercotkd/postdantic/issues"