[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pathCrawler"
authors = [{name="Matt Manes"}]
description = "I got tired of typing more than one line to get a recursive list of pathlib.Path objects for a given directory."
version = "0.1.1"
requires-python = ">=3.10"
dependencies = [
	"printBuddies"
]
readme = "README.md"
keywords = [
    "directory"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/matt-manes/pathCrawler"
"Documentation" = "https://github.com/matt-manes/pathCrawler/tree/main/docs"
"Source code" = "https://github.com/matt-manes/pathCrawler/tree/main/src/pathCrawler"