[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "puckluck"
authors = [{name = "Brock Tibert", email = "btibert3@gmail.com"}]
readme = "README.md"
dynamic = ["version", "description"]
requires-python = ">=3.8"
keywords = ["sports-analytics", "NHL", "hockey"]
dependencies = [
    "requests",
    "pandas",
]

[project.urls]
Home = "https://github.com/Btibert3/puckluck"


