[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "powerml_app"
version = "0.0.37"
authors = [
  { name="Jonathan Li", email="johnnyli@powerml.co" },
]
description = "PowerML python package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.23.5",
    "ratelimit>=2.2.1",
    "requests>=2.28.1",
    "sqlvalidator>=0.0.19",
    "python-configuration[yaml]",
    "jsonlines>=3.1.0",
    "tqdm==4.64.1",
    "transformers==4.25.1",
    "backoff==2.2.1",
    "nltk==3.8.1",
    "sql_metadata==2.6.0",
    "scikit_learn==1.2.0",
    "sentence_transformers==2.2.2",
    "pytest"
]

[tool.setuptools]
packages = ["powerml", "powerml.model", "powerml.utils", "powerml.fuzzy", "powerml.decorator", "powerml.filters", "powerml.generators"]