# pubchem API tools, in another way

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[project]
name= "pubchemTool"
version = "1.0.9"
authors = [
    {name= "Tomio13", email = "haraszti@dwi.rwth-aachen.de"},
]
readme = "Readme.md"
# summary = "Helper functions to dig into dict trees"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies=['dictDigUtils']
